### ISSUE TITLE
final_summary_table_gen_evo-I.R sub() function? 

### ISSUE THREAD

**Issue by sateeshperi** [Evolinc/Evolinc-I#15]
what does the "AGE_PLUS" refer to in line 422 of the R script?

(422) merge2$V1_2 <- sub("AGE_PLUS", "Yes", merge2$V1_2)

**Comment by andrew-d-l-nelson** [comment]
My guess is that is supposed to say "CAGE_PLUS" and is a typo. Not sure where the "AGE_PLUS" would come out (be noticed in an output) to make sure my guess is correct.

**Comment by upendrak** [comment]
Will be fixed in the new version
