### ISSUE TITLE
Using merged from gffcompare on DE

### ISSUE THREAD

**Issue by luciaq21** [Evolinc/Evolinc-I#19]
I tried running Evolinc-I on a cluster with Singularity and I have run into a number of issues, so I am opting to run it on the DE instead. I have the following question, my merged gtf is from gffcompare and not cuffcompare (since this program is now outdated and gffcompare is basically its newer version). Previously I had been told this was fine, but to use the -r flag. I was wondering what I can do when running it on the DE. Is there an option for this?

**Comment by andrew-d-l-nelson** [comment]
Hi luciaq21, shoot me an email (andrew.d.l.nelson at gmail.com) and I will walk you through the process. We can get your issues resolved!
