### ISSUE TITLE
IUPAC ambiguity codes in FASTA file

### ISSUE THREAD

**Issue by AndreinaCastillo** [Evolinc/Evolinc-I#8]
Error encountered when running Evolinc-I using FASTA files that have IUPAC ambiguity codes (e.g. KeyError: 'R'). Error was not found when ambiguous characters were replaced with 'N' and run with Evolinc-I again.

**Comment by upendrak** [comment]
@andrew-d-l-nelson this should fix it `sed -e '/^[^>]/s/[^ATGCatgc]/N/g' file.fa`. We will include that in the next version

**Comment by upendrak** [comment]
We are not going to include this code as we thought it was not that big of an issue..
